twig:
    file_name_pattern: '*.twig'
    form_themes: ['form/dsfr.html.twig']
    globals:
        app_env: '%env(APP_ENV)%'
        app_name: 'Oukilé?' 
        app_tagline: 'COMGENDGP'
        app_slug: 'Arrez de gérer votre matériel avec Excell!'

when@test:
    twig:
        strict_variables: true
